### ISSUE TITLE
Please don't force capitalisation in admin CSS

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#152]
### Short description of the enhancement

AdminThemeUikit has CSS rules:

```css
.uk-button {
    text-transform: capitalize;
}

.ui-button,.ui-button.ui-state-default,.ui-button.ui-state-hover {
    text-transform: capitalize;
}
```

If a developer wants their button text in title case they'll enter it in title case. The decision shouldn't be taken out of their hands by the admin CSS.

On the topic, I'd love it if the use of letter case could be reviewed across ProcessWire. At the moment there is a lot of inconsistency. There's an old issue about this: https://github.com/ryancramerdesign/ProcessWire/issues/1512

In my opinion, title case looks dated and gets very awkward for longer headings. There are [pros and cons](https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98) either way, but I come down firmly in favour of sentence case. My perception is that the majority of tasteful, modern layouts/interfaces use sentence case in headings and labels. Random examples:
https://github.com/features
https://www.dropbox.com/business/tour
https://stripe.com/about
